### ISSUE TITLE
When building image, use layer cache from pulled image

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-devops#19]
### Background

When I run:
```
tutor images pull openedx
```
it pulls `openedx:VERSION` from Dockerhub. Docker reuses any image layers that are already in the cache, and it's a no-op if I already have the latest image downloaded. Great.

When I run:
```
tutor dev dc build lms
```
it builds `openedx-dev:VERSION`, but it will *not* reuse the image layers pulled from `openedx:VERSION`, even though `openedx` shares several dozen layers with `openedx-dev`! It will start right from Step 1 at the top of the Dockerfile. That makes the build take way more time and bandwidth than it needs to.

### Tasks

TBD

**Comment by regisb** [comment]
Should we keep this issue open? After all, we are really not supposed to build images with `tutor dev dc build ...` anymore.

**Comment by kdmccormick** [comment]
Yes, I believe this is fixed.
